redshift:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{ env_var('PROFILES_YML_HOST') }}"
      user: "{{ env_var('PROFILES_YML_USER') }}"
      password: "{{ env_var('PROFILES_YML_PASS') }}"
      port: "{{ env_var('PROFILES_YML_PORT') }}"
      dbname: "{{ env_var('PROFILES_YML_DBNAME') }}"
      schema: "{{ env_var('PROFILES_YML_SCHEMA') }}"
      threads: 1